version: "3.7"

services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 8080:80
    networks:
      - mynetwork
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - mynetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # northwindrs:
  #   image: vietnamdevsgroup/northwind-rs:latest
  #   environment:
  #     ENVIRONMENT: production
  #     SERVER_URL: 0.0.0.0
  #     SERVER_PORT: 8089
  #     SERVER_LOG_LEVEL: info
  #     RUST_LOG: info
  #     JWT_SECRET_KEY: mySecretKey
  #     JWT_LIFETIME: 2
  #     DATABASE_URL: postgresql://postgres:root@postgres:5432/postgres
  #     DATABASE_AUTO_MIGRATION: "true"
  #   ports:
  #     - 8089:8089
  #   entrypoint: ["/layers/paketo-community_cargo-install/rust-bin/bin/api"]
  #   networks:
  #     - mynetwork
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

networks:
  mynetwork:
    name: mynetwork-network

volumes:
    postgres:
    pgadmin: